-- local status_ok, filetype = pcall(require, "filetype")
-- if status_ok then
--   require("filetype").setup({})
-- end

require "user.options"
require "user.globals"
require "user.utils"
require "user.plugins"
require "user.autocommands"
require "user.user-commands"
require "user.keymaps"
require "user.colorscheme"
require "user.cmp-spell"
require "user.cmp"
require "user.lsp"
require "user.treesitter"
require "user.telescope"
require "user.harpoon"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.quickscope"
require "user.hop"
require "user.matchup"
require "user.numb"
require "user.dial"
require "user.colorizer"
require "user.spectre"
require "user.zen-mode"
require "user.neoscroll"
require "user.todo-comments"
require "user.bookmark"
require "user.symbol-outline"
require "user.git-blame"
require "user.gist"
require "user.gitlinker"
-- require "user.session-manager"
require "user.auto-session"
-- require "user.surround"
require "user.notify"
require "user.ts-context"
require "user.registers"
require "user.telescope-file-browser"
require "user.sniprun"
-- require "user.copilot"
require "user.gps"
require "user.illuminate"
require "user.dap"
require "user.lir"
require "user.jabs"
require "user.lsp_colors"
require "user.thesaurus-query" -- sets up thesaurus stuff
require "user.aerial"
require "user.zk"
require "user.trouble"
-- require "user.shade"
require "user.keymap-amend"
